[versions]
agp = "8.11.0"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
coreKtx = "1.16.0"
desugar_jdk_libs = "2.1.5"
kotlin = "2.2.0"
kotlinxCoroutinesAndroid = "1.10.2"
ksp = "2.2.0-2.0.2"
libsuVersion = "6.0.0"
material = "1.14.0"
parcelize = "2.2.0"
remotepreferences = "0.8"
libxposed = "102.0.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-interpolator = { module = "androidx.interpolator:interpolator", version = "1.0.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
material = { module = "com.google.android.material:material", version.ref = "material" }
remotepreferences = { module = "com.crossbowffs.remotepreferences:remotepreferences", version.ref = "remotepreferences" }
su-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsuVersion" }
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposed" }

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "parcelize" }
